---
title: "chapter 3"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Logistic regression

Arto Vesterbacka

This chapter is about logistic regression using student data.

### Setting up libraries and working directory.

```{r Libraries}
library(knitr)
library(ggplot2)
library(dplyr)
library(tidyr)
#library(GGally)
```

```{r Working directory}
setwd("C:/koulu/mooc/intro to open data/IODS-project/") # change this if you wish to run the code on your computer
```

### Loading the data

```{r Data Loading}
dta_mat <- read.csv("student-mat.csv", sep=";", header=TRUE)
dta_por <- read.csv("student-por.csv", sep=";", header=TRUE)
dim(dta_mat)
dim(dta_por)
str(dta_mat)
str(dta_por)
```

### Joining the two dataset

Joining the two dataset with only the students present in both sets

```{r Joining the datasets}
join_by <- c("school","sex","age","address","famsize","Pstatus","Medu","Fedu","Mjob","Fjob","reason","nursery","internet")
mat <- inner_join(dta_mat, dta_por, by = join_by)
dim(mat)
str(mat)
```

```{r if_else_structure}

alc <- select(mat, one_of(join_by))

# the columns in the datasets which were not used for joining the data
notjoined_columns <- colnames(dta_mat)[!colnames(dta_mat) %in% join_by]

# for every column name not used for joining...
for(column_name in notjoined_columns) {
  # select two columns from 'math_por' with the same original name
  two_columns <- select(mat, starts_with(column_name, ignore.case = TRUE))
  # select the first column vector of those two columns
  first_column <- select(two_columns, 1)[[1]]

  # if that first column vector is numeric...
  if(is.numeric(first_column)) {
    # take a rounded average of each row of the two columns and
    # add the resulting vector to the alc data frame
    alc[column_name] <- round(rowMeans(two_columns))
  } else { # else if it's not numeric...
    # add the first column vector to the alc data frame
    alc[column_name] <- first_column
  }
}

```
### Mutating columns into one
```{r mutations}
alc <- mutate(alc, alc_use = (Dalc + Walc) / 2)
alc <- mutate(alc, high_use = alc_use > 2)
glimpse(alc)
```
```{r saving data to csv}
write.csv(x = alc, file="./data/alc_data.csv")
```


